# Lab 4 Multi-variable linear regression

In [1]:
import tensorflow as tf
import numpy as np

In [2]:
# file load
xy = np.loadtxt('data-01-test-score.csv', delimiter=',', dtype=np.float32)
# X and Y data
x_data = xy[:, 0:-1]
y_data = xy[:, [-1]]

In [3]:
# Make sure the shape and data are OK
print(x_data, "\nx_data shape:", x_data.shape)
print(y_data, "\ny_data shape:", y_data.shape)

[[ 73.  80.  75.]
 [ 93.  88.  93.]
 [ 89.  91.  90.]
 [ 96.  98. 100.]
 [ 73.  66.  70.]
 [ 53.  46.  55.]
 [ 69.  74.  77.]
 [ 47.  56.  60.]
 [ 87.  79.  90.]
 [ 79.  70.  88.]
 [ 69.  70.  73.]
 [ 70.  65.  74.]
 [ 93.  95.  91.]
 [ 79.  80.  73.]
 [ 70.  73.  78.]
 [ 93.  89.  96.]
 [ 78.  75.  68.]
 [ 81.  90.  93.]
 [ 88.  92.  86.]
 [ 78.  83.  77.]
 [ 82.  86.  90.]
 [ 86.  82.  89.]
 [ 78.  83.  85.]
 [ 76.  83.  71.]
 [ 96.  93.  95.]] 
x_data shape: (25, 3)
[[152.]
 [185.]
 [180.]
 [196.]
 [142.]
 [101.]
 [149.]
 [115.]
 [175.]
 [164.]
 [141.]
 [141.]
 [184.]
 [152.]
 [148.]
 [192.]
 [147.]
 [183.]
 [177.]
 [159.]
 [177.]
 [175.]
 [175.]
 [149.]
 [192.]] 
y_data shape: (25, 1)


In [4]:
# placeholders for a tensor that will be always fed.
X = tf.placeholder(tf.float32, shape=[None, 3])
Y = tf.placeholder(tf.float32, shape=[None, 1])

W = tf.Variable(tf.random_normal([3, 1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

In [5]:
# Hypothesis
hypothesis = tf.matmul(X, W) + b

In [6]:
# Simplified cost/loss function
cost = tf.reduce_mean(tf.square(hypothesis - Y))

In [7]:
# Minimize
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

In [11]:
# Launch the graph in a session.
with tf.Session() as sess:
    # Initializes global variables in the graph.
    sess.run(tf.global_variables_initializer())
    for step in range(2001):
        cost_val, hy_val, _ = sess.run([cost, hypothesis, train],
                                      feed_dict = {X:x_data, Y:y_data})
        if step % 200 == 0:
            print(step, "Cost:", cost_val, "\nPrediction:\n", hy_val)

0 Cost: 12491.22 
Prediction:
 [[47.82298 ]
 [56.426327]
 [55.72433 ]
 [63.981327]
 [40.37717 ]
 [35.36679 ]
 [53.58081 ]
 [47.556293]
 [56.8483  ]
 [60.277782]
 [47.93282 ]
 [48.268406]
 [53.988148]
 [40.169548]
 [54.087868]
 [60.57658 ]
 [33.928764]
 [66.34241 ]
 [51.109875]
 [46.593864]
 [61.244358]
 [56.42696 ]
 [57.54689 ]
 [40.017487]
 [56.921337]]
200 Cost: 20.556587 
Prediction:
 [[152.92206 ]
 [182.6649  ]
 [180.16328 ]
 [199.35468 ]
 [136.75827 ]
 [106.183205]
 [154.71162 ]
 [122.250145]
 [174.62488 ]
 [169.02823 ]
 [145.49724 ]
 [144.37564 ]
 [182.70352 ]
 [147.37932 ]
 [155.65482 ]
 [188.54327 ]
 [136.18932 ]
 [187.63322 ]
 [173.85791 ]
 [156.40549 ]
 [179.87825 ]
 [174.71407 ]
 [170.70464 ]
 [146.3371  ]
 [187.83672 ]]
400 Cost: 18.80192 
Prediction:
 [[153.017  ]
 [182.71515]
 [180.25717]
 [199.31818]
 [136.89505]
 [106.06212]
 [154.49553]
 [121.82803]
 [174.48726]
 [168.58806]
 [145.41254]
 [144.21062]
 [182.94188]
 [147.77194]
 [155.41281]
 [188.46777]
 [136.71207]
 [18