# Lab 4 Multi-variable linear regression

In [1]:
import tensorflow as tf

In [2]:
# X and Y data
x_data = [[73., 80., 75.],
          [93., 88., 93.],
          [89., 91., 90.],
          [96., 98., 100.],
          [73., 66., 70.]]
y_data = [[152.],
          [185.],
          [180.],
          [196.],
          [142.]]

In [3]:
# placeholders for a tensor that will be always fed.
X = tf.placeholder(tf.float32, shape=[None, 3])
Y = tf.placeholder(tf.float32, shape=[None, 1])

W = tf.Variable(tf.random_normal([3, 1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

In [4]:
# Hypothesis
hypothesis = tf.matmul(X, W) + b

In [5]:
# Simplified cost/loss function
cost = tf.reduce_mean(tf.square(hypothesis - Y))

In [7]:
# Minimize
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

In [11]:
# Launch the graph in a session
with tf.Session() as sess:
    # Initializes global variables in the graph.
    sess.run(tf.global_variables_initializer())

    for step in range(2001):
        cost_val, hy_val, _ = sess.run(
            [cost, hypothesis, train], feed_dict={X: x_data, Y: y_data})
        if step % 200 == 0:
            print(step, "Cost: ", cost_val, "\nPrediction:\n", hy_val)

0 Cost:  8313.457 
Prediction:
 [[72.0223  ]
 [86.254234]
 [85.01196 ]
 [94.00806 ]
 [64.572334]]
200 Cost:  3.6998734 
Prediction:
 [[152.78683]
 [183.552  ]
 [180.765  ]
 [198.28316]
 [138.84001]]
400 Cost:  3.4446225 
Prediction:
 [[152.67474]
 [183.62991]
 [180.732  ]
 [198.24901]
 [138.95093]]
600 Cost:  3.2145545 
Prediction:
 [[152.56879]
 [183.70358]
 [180.70084]
 [198.21623]
 [139.05624]]
800 Cost:  3.0070727 
Prediction:
 [[152.46866]
 [183.77325]
 [180.67148]
 [198.18478]
 [139.1563 ]]
1000 Cost:  2.8198822 
Prediction:
 [[152.37404]
 [183.83916]
 [180.64378]
 [198.15462]
 [139.25134]]
1200 Cost:  2.6509285 
Prediction:
 [[152.28462]
 [183.90147]
 [180.61768]
 [198.12566]
 [139.34163]]
1400 Cost:  2.4982944 
Prediction:
 [[152.20015]
 [183.9604 ]
 [180.59308]
 [198.09782]
 [139.42744]]
1600 Cost:  2.3603432 
Prediction:
 [[152.12035]
 [184.01613]
 [180.56993]
 [198.07109]
 [139.50902]]
1800 Cost:  2.235588 
Prediction:
 [[152.04495]
 [184.06879]
 [180.5481 ]
 [198.04535]
 [1