# Lab 4 Multi-variable linear regression

In [1]:
import tensorflow as tf

In [2]:
# X and Y data
x1_data = [73., 93., 89., 96., 73.]
x2_data = [80., 88., 91., 98., 66.]
x3_data = [75., 93., 90., 100., 70.]

y_data = [152., 185., 180., 196., 142.]

In [6]:
# placeholders for a tensor that will be always fed.
x1 = tf.placeholder(tf.float32)
x2 = tf.placeholder(tf.float32)
x3 = tf.placeholder(tf.float32)

Y = tf.placeholder(tf.float32)

w1 = tf.Variable(tf.random_normal([1]), name='weight1')
w2 = tf.Variable(tf.random_normal([1]), name='weight2')
w3 = tf.Variable(tf.random_normal([1]), name='weight3')
b = tf.Variable(tf.random_normal([1]), name='bias')

In [7]:
hypothesis = x1 * w1 + x2 * w2 + x3 * w3 + b

In [8]:
# cost/loss function
cost = tf.reduce_mean(tf.square(hypothesis - Y))

In [20]:
# Minimize. Need a very small learning rate for this data set
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

In [22]:
# Launch the graph in a session.
with tf.Session() as sess:
    # Initializes global variables in the graph.
    sess.run(tf.global_variables_initializer())
    for step in range(2001):
        cost_val, hy_val, _ = sess.run([cost, hypothesis, train],
                                       feed_dict={x1: x1_data, x2: x2_data, x3: x3_data, Y: y_data})
        if step % 200 == 0:
            print(step, "Cost: ", cost_val, "\nPrediction:\n", hy_val)

0 Cost:  276777.8 
Prediction:
 [-311.15854 -379.1439  -370.8442  -405.9398  -288.52756]
200 Cost:  6.025833 
Prediction:
 [155.4504  182.04654 181.91795 196.03102 139.58722]
400 Cost:  5.4472003 
Prediction:
 [155.26863 182.17064 181.86162 195.99524 139.74586]
600 Cost:  4.927867 
Prediction:
 [155.0964  182.28822 181.80821 195.96155 139.89601]
800 Cost:  4.4616 
Prediction:
 [154.93312 182.39966 181.75755 195.92982 140.03809]
1000 Cost:  4.0429764 
Prediction:
 [154.77835 182.50526 181.70947 195.89998 140.17253]
1200 Cost:  3.6671462 
Prediction:
 [154.63164 182.60533 181.6639  195.87189 140.29976]
1400 Cost:  3.3296344 
Prediction:
 [154.49255 182.70021 181.62065 195.84546 140.42015]
1600 Cost:  3.0265737 
Prediction:
 [154.3607  182.79012 181.5796  195.82062 140.53404]
1800 Cost:  2.754427 
Prediction:
 [154.2357  182.87532 181.5407  195.79727 140.64182]
2000 Cost:  2.5099895 
Prediction:
 [154.11717 182.95607 181.50375 195.77536 140.74376]
