In [1]:
import tensorflow as tf
import numpy as np

In [2]:
def min_max_scaler(data):
    numerator = data - np.min(data, 0)
    denominator = np.max(data, 0) - np.min(data, 0)
    # noise term prevents the zero division
    return numerator / (denominator + 1e-7)

In [3]:
xy = np.array(
    [
        [828.659973, 833.450012, 908100, 828.349976, 831.659973],
        [823.02002, 828.070007, 1828100, 821.655029, 828.070007],
        [819.929993, 824.400024, 1438100, 818.97998, 824.159973],
        [816, 820.958984, 1008100, 815.48999, 819.23999],
        [819.359985, 823, 1188100, 818.469971, 818.97998],
        [819, 823, 1198100, 816, 820.450012],
        [811.700012, 815.25, 1098100, 809.780029, 813.669983],
        [809.51001, 816.659973, 1398100, 804.539978, 809.559998],
    ]
)

# very important. It does not work without it.
xy = min_max_scaler(xy)
print(xy)

[[0.99999999 0.99999999 0.         1.         1.        ]
 [0.70548491 0.70439552 1.         0.71881782 0.83755791]
 [0.54412549 0.50274824 0.57608696 0.606468   0.6606331 ]
 [0.33890353 0.31368023 0.10869565 0.45989134 0.43800918]
 [0.51436    0.42582389 0.30434783 0.58504805 0.42624401]
 [0.49556179 0.42582389 0.31521739 0.48131134 0.49276137]
 [0.11436064 0.         0.20652174 0.22007776 0.18597238]
 [0.         0.07747099 0.5326087  0.         0.        ]]


In [4]:
x_data = xy[:, 0:-1]
y_data = xy[:, [-1]]

# placeholders for a tensor that will be always fed.
X = tf.placeholder(tf.float32, shape=[None, 4])
Y = tf.placeholder(tf.float32, shape=[None, 1])

W = tf.Variable(tf.random_normal([4, 1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

# Hypothesis
hypothesis = tf.matmul(X, W) + b

# Simplified cost/loss function
cost = tf.reduce_mean(tf.square(hypothesis - Y))

# Minimize
train = tf.train.GradientDescentOptimizer(learning_rate=1e-5).minimize(cost)

# Launch the graph in a session.
with tf.Session() as sess:
    # Initializes global variables in the graph.
    sess.run(tf.global_variables_initializer())

    for step in range(101):
        _, cost_val, hy_val = sess.run(
            [train, cost, hypothesis], feed_dict={X: x_data, Y: y_data}
        )
        print(step, "Cost: ", cost_val, "\nPrediction:\n", hy_val)

0 Cost:  0.9529488 
Prediction:
 [[1.9714628 ]
 [2.2530305 ]
 [1.6950961 ]
 [1.0931056 ]
 [1.4229615 ]
 [1.4180682 ]
 [0.76727045]
 [0.9947243 ]]
1 Cost:  0.9528785 
Prediction:
 [[1.9714153]
 [2.2529829]
 [1.6950566]
 [1.093075 ]
 [1.4229252]
 [1.4180331]
 [0.7672464]
 [0.9947002]]
2 Cost:  0.95280826 
Prediction:
 [[1.9713676]
 [2.2529352]
 [1.6950169]
 [1.0930444]
 [1.4228892]
 [1.4179982]
 [0.7672224]
 [0.9946761]]
3 Cost:  0.9527381 
Prediction:
 [[1.9713202 ]
 [2.2528877 ]
 [1.6949774 ]
 [1.0930139 ]
 [1.422853  ]
 [1.417963  ]
 [0.76719844]
 [0.99465203]]
4 Cost:  0.9526678 
Prediction:
 [[1.9712723 ]
 [2.25284   ]
 [1.6949377 ]
 [1.0929832 ]
 [1.4228168 ]
 [1.4179282 ]
 [0.7671744 ]
 [0.99462795]]
5 Cost:  0.9525975 
Prediction:
 [[1.9712249]
 [2.2527924]
 [1.694898 ]
 [1.0929527]
 [1.4227808]
 [1.417893 ]
 [0.7671504]
 [0.9946039]]
6 Cost:  0.95252717 
Prediction:
 [[1.9711771 ]
 [2.2527447 ]
 [1.6948584 ]
 [1.0929221 ]
 [1.4227445 ]
 [1.4178581 ]
 [0.76712644]
 [0.99457973]]
